project/app/urls.py
from django.urls import path
from app.views import LoginPage,MonthScedule,RoleData,IndividuaWithSchedule,IndividualFormCalendar,GoalData, GoalMonthUpdate, GoalYearUpdate, Login, Logout, AccountRegistration, bulletinboard, home, post_detail, MonthCalendar, MyCalendar, MonthWithScheduleCalendar
GoalData,GoalMonthUpdate, GoalYearUpdate, 
urlpatterns = [
    path('register/', AccountRegistration.as_view(), name='register'),
    path('login/', Login, name='login'),
    path('loginpage/', LoginPage, name='loginpage'),
    path("logout/", Logout, name="logout"),
    path("home/", home, name="home"),
    path("post_detail/<slug:slug>/", post_detail, name='post_detail'),
    path('mycalendar/', MyCalendar.as_view(), name='mycalendar'),
    path('mycalendar/<int:year>/<int:month>/<int:day>/', MyCalendar.as_view(), name='mycalendar'),  
    path('bulletinboard/', bulletinboard, name="bulletinboard"),
    path('month/', MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/<int:day>/', MonthCalendar.as_view(), name='month'),
    path('month_with_schedule/', MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('month_with_schedule/<int:year>/<int:month>/<int:day>/', MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('goal_form/',GoalData.as_view() , name='goal_form'),
    path('goal_form/<int:year>/<int:month>/<int:day>/',GoalData.as_view(), name='goal_form'),
    path("goal_month_update/<int:pk>/<int:year>/<int:month>/<int:day>/", GoalMonthUpdate.as_view(), name="goal_month_update"),
    path("goal_year_update/<int:pk>/<int:year>/<int:month>/<int:day>/", GoalYearUpdate.as_view(), name="goal_year_update"),
    path('individual_calendar/', IndividualFormCalendar.as_view(), name='individual_calendar'),
    path('individual_calendar/<int:year>/<int:month>/<int:day>/,', IndividualFormCalendar.as_view(), name='individual_calendar'),
    path('individual_schedule/<int:pk>/', IndividuaWithSchedule.as_view(), name="individual_schedule"),
    path('individual_schedule/<int:pk>/<int:year>/<int:month>/<int:day>/', IndividuaWithSchedule.as_view(), name='individual_schedule'),
    path('role/', RoleData.as_view(), name='role'),
    path('month_schedule/', MonthScedule.as_view(), name='month_schedule'),
    path('month_schedule/<int:year>/<int:month>/<int:day>/', MonthScedule.as_view(), name='month_schedule'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import frontpages, LoginPage

urlpatterns = [
    path('loginpage/', LoginPage, name='loginpage'),
    path('', include('app.urls'), name="app"),
    path('admin/', admin.site.urls),
    path("", frontpages.as_view(), name="frontpage"),
    path("<int:year>/<int:month>/<int:day>/", frontpages.as_view(), name="frontpage")
]

project/app/models.py
from django.db import models
from django.db import models
# ユーザー認証
from django.contrib.auth.models import User
#時間
from django.utils import timezone
import random 
import datetime

#urlの末尾を同一にしないための関数
def random_url():
     chars = '0123456789abcdefghijkmnopqrstuvwxzyABCDEFGHIJKLMNOPQRSTUVWXYZ'
     url = ''.join(random.choice(chars)for i in range(16))
     return url


#dbへデータを保存するためのクラス
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField('タイトル',max_length=255)
    slug = models.SlugField(unique=True, default=random_url)
    intro = models.TextField()
    body = models.TextField('内容')
    posted_date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    posted_date = models.DateTimeField(auto_now_add=True)
    
#調べる
class Account(models.Model):
    
    # ユーザー認証のインスタンス(1vs1関係)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # 追加フィールド
    last_name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    account_image = models.ImageField(upload_to="profile_pics",blank=True)
    def __str__(self):
        return self.user.username

class Schedule(models.Model):
    """スケジュール"""
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

class Goal(models.Model):
    year = models.CharField("今年の目標",max_length=100)
    month = models.CharField("今月の目標",max_length=100)
    date = models.DateField("日付")

class IndividualSchedule(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return str(self.user)


class Role(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField("やること", max_length=50)


class MonthGoal(models.Model):
    goal = models.CharField('スケジュール', max_length=50)
    date = models.DateField()

project/app/templates/blog/bulletinboard.html
{% extends "blog/base.html" %}
{% block content %}
<body>
{% for post in posts %}
<div class="post block">
    <h2 class="subtitle">{{post.title}}</h2>
    <small>投稿された時間：{{post.posted_date}}</small>
    <p>{{post.user}}</p>
    <p>{{post.intro}}</p>
    <a href="{% url 'post_detail' post.slug %}">もっと読む</a>
    <hr />
</div>
{% endfor %}
    {% if user.is_authenticated %}
    <h2 class="subtitle">投稿を追加</h2>
    <form action="." method="post">
        {% csrf_token %}
        {{post_forms.as_p}}
        <div class="field">
            <div class="control">
                <button class="button is-danger">送信</button>
            </div>
        </div>
    </form>
    {% else %}
    <div>
        <p>投稿するにはログインしてください</p>
        <a href="{% url 'login' %}" class="btn">ログイン</a>
    </div>
    {% endif %}
</body>
{% endblock %}

project/app/templates/blog/calendarpage.html
{% extends "blog/base.html" %}
{% block content %}
{% for post in calendar_post %}
<p>{{post}}</p>
{% endfor %}
{% endblock %}

project/app/templates/blog/calender.html
<a href="{% url 'mycalendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'mycalendar' month_next.year month_next.month month_next.day %}">次月</a>

<body>
    
    <hr>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                {% if month_current.month != day.month %}
                    {{ day | date:"m/d" }}
                {% else %}
                    {{ day.day }}
                {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
 </body>

project/app/templates/blog/goal_update.html
{% extends "blog/base.html" %}
{% block content %}
<body>
    <h1>目標変更</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="保存">
    </form>
    <hr>
    <a href="{% url 'goal_form'%}">戻る</a>
</body>
{% endblock %}

project/app/templates/blog/goal_year_update.html
{% extends "blog/base.html" %}
{% block content %}
<body>
    <h1>目標変更</h1>
    <form action="" method="POST">
        <input type="hidden" name="month" value="{{goal_first.month}}">
        <p>今年の目標：{{form.year}}</p>
        <button type="submit" class="btn btn-primary">送信</button>
        {% csrf_token %}
        </form>
    <hr>
        <a href="{{request.META.HTTP_REFERER}}">戻る</a>
</body>
{% endblock %}

project/app/templates/blog/individual_calendar.html
{% extends 'blog/base.html' %}
{% block content %}
<a href="{% url 'individual_calendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'individual_calendar' month_next.year month_next.month month_next.day %}">次月</a>
        <table class="table">
        {% if user.is_authenticated %}
            <p>{{ user.get_username }}さん、{{ month_current | date:"Y年m月" }}のスケジュールを記入してください！</p>
            <thead>
            <tr>
                {% for w in week_names %}
                    <th>{{ w }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for week_day_schedles in month_day_schedules %}
                <tr>
                    {% for day, schedules in week_day_schedles.items %}
                        {% if now == day %}
                            <td class="table-success">
                                {% else %}
                            <td>
                        {% endif %}
        
                    <div>
                        {% if month_current.month != day.month %}
                            <a href="{% url 'individual_calendar' day.year day.month day.day %}">{{ day | date:"m/d" }}</a>
                        {% else %}
                            <a href="{% url 'individual_calendar' day.year day.month day.day %}">{{day.day}}</a>
                        {% endif %}
        
                        {% for schedule in schedules %}
                            <p>{{ schedule.start_time }} - {{ schedule.end_time }}</p>
                            <p>{{ schedule.summary }}</p>
                            <p>{{ schedule.description | linebreaks }}</p>
                        {% endfor %}
                    </div>
                    </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
            <div>
                <p>{{ day_current | date:"m月d日" }}の予定を書く</p>
                <form action="" method="POST">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        <div class="form-group row">
                            <label for="{{ field.id_for_label }}"
                                class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                            <div class="col-sm-8">
                                {{ field }}
                                {{ field.errors }}
                            </div>
                        </div>
                    {% endfor %}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">送信</button>
                </form>
            </div>
        {% else %}
        <div>
            <p>投稿するにはログインしてください</p>
            <a href="{% url 'login' %}" class="btn">ログイン</a>
        </div>
        {% endif %}
        </table>
{% endblock %}

project/app/templates/blog/individual_schedule.html
{% extends 'blog/base.html' %}
{% block content %}
    <a href="{% url 'individual_schedule' name_pk month_previous.year month_previous.month month_previous.day %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'individual_schedule' name_pk month_next.year month_next.month month_next.day %}">次月</a>

        <table class="table">
        {% for name in account %}
            {% if name_pk == name.pk %}
            <p>{{name}}さんのスケジュール</p>
            {% endif %}
        {% endfor %}
            <thead>
            <tr>
                {% for w in week_names %}
                    <th>{{ w }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for week_day_schedles in month_day_schedules %}
                <tr>
                    {% for day, schedules in week_day_schedles.items %}
                        {% if now == day %}
                            <td class="table-success">
                                {% else %}
                            <td>
                        {% endif %}
        
                    <div>
                        {% if month_current.month != day.month %}
                            <p>{{ day | date:"m/d" }}</p>
                        {% else %}
                            <p>{{day.day}}</p>
                        {% endif %}
                            {% for schedule in schedules %}
                                {% if page_name.user == schedule.user %}
                                    <p>{{ schedule.start_time }} - {{ schedule.end_time }}</p>
                                    <p>{{ schedule.summary }}</p>
                                    <p>{{ schedule.description | linebreaks }}</p> 
                                {% endif %}
                            {% endfor %}
                    </div>
                    </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}

project/app/templates/blog/month.html
<table class="table">
    <thead>
    <tr>
        {% for w in week_names %}
            <th>{{ w }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week_day_schedles in month_day_schedules %}
        <tr>
            {% for day, schedules in week_day_schedles.items %}
                {% if now == day %}
                    <td class="table-success">
                        {% else %}
                    <td>
                {% endif %}

            <div>
                {% if month_current.month != day.month %}
                    <a href="{% url 'month' day.year day.month day.day %}">{{ day | date:"m/d" }}</a>
                {% else %}
                    <a href="{% url 'month' day.year day.month day.day %}">{{day.day}}</a>
                {% endif %}

                {% for schedule in schedules %}
                    <p>{{ schedule.start_time }} - {{ schedule.end_time }}</p>
                    <p>{{ schedule.summary }}</p>
                    <p>{{ schedule.description | linebreaks }}</p>
                {% endfor %}
            </div>
            </td>
            {% endfor %}
        </tr>
    {% endfor %}
    <a href="{% url 'month_with_forms' %}">スケジュール投稿はこちら！</a>
    </tbody>
</table>

project/app/templates/blog/month_with_schedule.html
{% extends 'blog/base.html' %}
{% block content %}
<a href="{% url 'month_with_schedule' month_previous.year month_previous.month month_previous.day %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'month_with_schedule' month_next.year month_next.month month_next.day %}">次月</a>
    {% for name in account %}
    <a href="{% url 'individual_schedule' name.pk %}">{{name}}</a>
    {% endfor %}
    <hr>
    {% for month in year_month_day %}
    <a href="{% url 'individual_calendar' month.year month.month month.day %}">個人カレンダーの投稿フォーム</a>
    {% endfor %}
        <table class="table">
            <thead>
            <tr>
                {% for w in week_names %}
                    <th>{{ w }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for week_day_schedles in month_day_schedules %}
                <tr>
                    {% for day, schedules in week_day_schedles.items %}
                        {% if now == day %}
                            <td class="table-success">
                                {% else %}
                            <td>
                        {% endif %}
        
                    <div>
                        {% if month_current.month != day.month %}
                            <a href="{% url 'month_with_schedule' day.year day.month day.day %}">{{ day | date:"m/d" }}</a>
                        {% else %}
                            <a href="{% url 'month_with_schedule' day.year day.month day.day %}">{{day.day}}</a>
                        {% endif %}
        
                        {% for schedule in schedules %}
                            <p>{{ schedule.start_time }} - {{ schedule.end_time }}</p>
                            <p>{{ schedule.summary }}</p>
                            <p>{{ schedule.description | linebreaks }}</p>
                        {% endfor %}
                    </div>
                    </td>
                    {% endfor %}
                </tr>
            {% endfor %}
                <div>
                    <p>{{ day_current | date:"Y年m月d日" }}の予定を書く</p>
                    <form action="" method="POST">
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <div class="form-group row">
                                <label for="{{ field.id_for_label }}"
                                    class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                                <div class="col-sm-8">
                                    {{ field }}
                                    {{ field.errors }}
                                </div>
                            </div>
                        {% endfor %}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">送信</button>
                    </form>
                </div>
                <hr>
                <div>
                    <h1>月間スケジュール</h1>
                        {% for fourschedules in monthschedules %}
                        <div>
                            {% for month, schedules in fourschedules.items %}
                                <a href="{% url 'month_with_schedule' month.year month.month month.day %}">{{month.month}}月</a>
                                {% for schedule in schedules %}
                                    {{schedule.goal}}
                                {% endfor %}
                            {% endfor %}
                        </div>
                        {% endfor %}
                        <div>
                        {% for month in year_month_day %}
                        <a href="{% url 'month_schedule' month.year month.month month.day %}">月のスケジュール投稿はこちら！</a>
                        {% endfor %}
                        </div>
                        <hr>
                </div>
            </tbody>
        </table>
{% endblock %}

project/app/templates/blog/mycalendar.html
{% extends 'blog/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<p>{{ user.get_username }}でログイン中</p>
{% else %}
<p>ログインなし</p>
{% endif %}
<p>トップページは
<a href="{% url 'frontpage' %}">こちら</a></p>
    <div class="row">
        <div class="col-md-3">
            {% include 'blog/calender.html' %}
            <hr>
            <div class="col-md-9">
                {% include 'blog/week.html' %}
            </div>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">送信</button>
            </form>
        </div>
    </div>
{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

project/app/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="title">{{post.title}}</h1>
    <small>Posted at {{post.posted_date}}}</small>
    <p>{{post.user}}</p>
    <p>{{post.intro}}</p>
    <p>{{post.body}}</p>
    <hr />


    <!--　コメントされたものを表示-->
    <h2 class="subtitle">コメント</h2>

    {% for comment in post.comments.all %}
    <article class="media">
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>
                        {{comment.name}}
                        <small>{{comment.posted_date}}</small>
                    </strong>
                    <br />
                    {{comment.body}}
                </p>
            </div>
        </div>
    </article>
    {% empty %}
    <div class="notification">
        <p>コメントはまだありません。</p>
    </div>
    <hr>
    {% endfor %}
    <!-- コメント投稿エリア　-->
    <h2 class="subtitle">コメントを追加</h2>
    <form action="." method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div class="field">
            <div class="control">
                <button class="button is-danger">送信</button>
            </div>
        </div>
    </form>
{% endblock %}

project/app/templates/blog/register.html
<body>
<h1>新規登録</h1>

 {% if AccountCreate %}
   <h1>登録完了!</h1>

 {% else %}
   <div class="reg">
   <table class="reg_form">

   <form enctype="multipart/form-data" method="post">
   {% csrf_token %}
   {{ account_form.as_table }}
   {{ add_account_form.as_table }}
   <tr><td></td><td>
   <input class="btn" type="submit" name="" value="登録">
   </td></tr>
   </form>

   </table>
   </div>
 {% endif %}

project/app/templates/blog/role.html
{% extends 'blog/base.html' %}
{% block content %}
{% if user.is_authenticated %}
    <p>{{ user.get_username }}でログイン中</p>
    {% else %}
{% endif %}
<h1>当番</h1>
{% for role in role_post %}
    <p>{{role.role}}：{{role.user}}</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
        <form action="" method="POST">
            <p>{{form.as_p}}</p>
            <button type="submit" class="btn btn-primary">送信</button>
            {% csrf_token %}
        </form>
{% else %}
    <div>
        <p>投稿するにはログインしてください</p>
        <a href="{% url 'login' %}" class="btn">ログイン</a>
    </div>
{% endif %}
{% endblock %}

project/app/templates/blog/week.html
 <table class="table table-bordered">
    <thead>
    <tr>
        {% for w in week_names %}
            <th>{{ w }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    <tr>
        {% for day, schedules in week_day_schedules.items %}
            <td>
                <!-- 日付 -->
                {% if week_first.month != day.month %}
                    <a href="{% url 'frontpage' day.year day.month day.day %}">{{ day | date:"m/d" }}</a>
                {% else %}
                    <a href="{% url 'frontpage' day.year day.month day.day %}">{{day.day}}</a>
                {% endif %}
                <br>

                <!-- その日のスケジュール -->
                {% for s in schedules %}
                    {{ s.start_time }} - {{ s.end_time }}<br>
                    {{ s.summary }}<br>
                    {{ s.description | linebreaks }}
                {% endfor %}
            </td>
        {% endfor %}
    </tr>
    </tbody>
</table>